const ACTION_TYPES = {
  CHECK_SESSION: 'CHECK_SESSION',
  FETCH_START: 'FETCH_START',
  FETCH_SUCCESS: 'FETCH_SUCCESS',
  FETCH_FAILED: 'FETCH_FAILED',
  RESET: 'RESET',
  SET_TASKS: 'SET_TASKS',
  CREATE_TASK: 'CREATE_TASK',
  UPDATE_TASK: 'UPDATE_TASK',
  DELETE_TASK: 'DELETE_TASK',
};

export { ACTION_TYPES };
