const ACTION_TYPES = {
  // User details
  GET_DETAILS_REQUEST: 'GET_DETAILS_REQUEST',
  GET_DETAILS_SUCCEED: 'GET_DETAILS_SUCCEED',
  GET_DETAILS_FAILED: 'GET_DETAILS_FAIELD',
  // User registration
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCEED: 'REGISTER_SUCCEED',
  REGISTER_FAILED: 'REGISTER_FAILED',
  // User login
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCEED: 'LOGIN_SUCCEED',
  LOGIN_FAILED: 'LOGIN_FAILED',
  // Email verification
  VERIFICATION_REQUEST: 'VERIFICATION_REQUEST',
  VERIFICATION_SUCCEED: 'VERIFICATION_SUCCEED',
  VERIFICATION_FAILED: 'VERIFICATION_FAILED',
  // Resend email verification
  RESEND_VERIFICATION_REQUEST: 'RESEND_VERIFICATION_REQUEST',
  RESEND_VERIFICATION_SUCCEED: 'RESEND_VERIFICATION_SUCCEED',
  RESEND_VERIFICATION_FAILED: 'RESEND_VERIFICATION_FAILED',
  // Get tasks
  GET_TASKS_REQUEST: 'GET_TASKS_REQUEST',
  GET_TASKS_SUCCEED: 'GET_TASKS_SUCCEED',
  GET_TASKS_FAILED: 'GET_TASKS_FAILED',
  // Create task
  CREATE_TASK_REQUEST: 'CREATE_TASK_REQUEST',
  CREATE_TASK_SUCCEED: 'CREATE_TASK_SUCCEED',
  CREATE_TASK_FAILED: 'CREATE_TASK_FAILED',
  // Update task
  UPDATE_TASK_REQUEST: 'UPDATE_TASK_REQUEST',
  UPDATE_TASK_SUCCEED: 'UPDATE_TASK_SUCCEED',
  UPDATE_TASK_FAILED: 'UPDATE_TASK_FAILED',
  // Delete task
  DELETE_TASK_REQUEST: 'DELETE_TASK_REQUEST',
  DELETE_TASK_SUCCEED: 'DELETE_TASK_SUCCEED',
  DELETE_TASK_FAILED: 'DELETE_TASK_FAILED',
  UPDATE_TASK: 'UPDATE_TASK',
  DELETE_TASK: 'DELETE_TASK',
  // Reset
  RESET_ERROR: 'RESET_ERROR',
  RESET: 'RESET',
};

export { ACTION_TYPES };
